Add login screen
JustOrgYou/joy_app pull request #4
Opened 2023-07-02 15:43 UTC by frog-da

2023-07-02 16:11 UTC, Demezy requested changes
Самое основное - надо вынести проверку на креды из верстки. В идеале сделать AuthService и там замокать функции. 

то есть должно быть что-то типо

auth_servide_mock.dart
```dart
class AuthServiceMock implements AuthService{...}
```

auth_providers.dart
```dart
final authServiceProvider = Provider<AuthService>((ref) => AuthServiceMock() }
```

в верстке используем ConsumerStatefulWidget | ConsumerWidget
```dart
Widget buid(...){
final authService = ref.watch(authServideProvider);
...
authServide.auth('login', 'pass');
}
```

2023-07-02 16:11 UTC, Demezy commented on lib/login/login.dart
> +class LogIn extends StatefulWidget {
LogIn, как мне кажется, достаточно частый термин. В будущем может возникнуть путаница вполне возможно что будет Login/Auth Repository/Service, и какой-нибудь loginProvider, а еще, какой нибудь OTALogin... может переименовать в EmailPasswordLogin?

2023-07-02 16:11 UTC, Demezy commented on lib/login/login.dart
> +  bool? isChecked;
Если переменная существует только на экране, можно сделать `final isChecked = ValueNotifer(false)`
и потом в `initState` повесить коллбек на обновление
```
isChecked.addListener(()=>setState((){}))
```
тогда в коде просто делается 
isChecked.value = ...
и все само обновляется

в этом варианте надо не забыть в `dispose` закрыть нотифаер

2023-07-02 16:11 UTC, Demezy commented on lib/login/login.dart
> +            if (isChecked == false) Text(errorMessage),
тогда думаю и формы можно покрасить в красный

2023-07-02 16:11 UTC, Demezy commented on lib/login/login.dart
> +    if (email.text == 'asd@gmail.com' && password.text == '1234') {
вынеси эту проверку в мок сервис, а тут только по его ответу меняй ui

2023-07-02 16:11 UTC, Demezy commented on lib/login/login.dart
> +  Future<void> isCheckedAsync() async {
Не совсем понял что делает функция isCheckedAsync... тут немного подушню, но название должно отражать суть. Предлагаю validateCredentials или что-то такое. Логика должна быть в сервисе

2023-07-02 16:11 UTC, Demezy commented on lib/login/login.dart
> +  String errorMessage = 'Invalid email or password.';
так как поля задаются единожды лучше маркировать их как `final`

2023-07-02 16:11 UTC, Demezy commented on lib/login/login.dart
> +  bool? isChecked;
зачем делать её nullable?

2023-07-02 16:26 UTC, frog-da commented on lib/login/login.dart
> +  bool? isChecked;
чтобы изначально не было ошибки на экране, но это потом всё равно переделается

2023-07-03 14:20 UTC, merged

2023-07-03 16:01 UTC, Demezy commented on lib/email_password_login/email_password_login.dart
> +      // ignore: use_build_context_synchronously
есть `context.mounted` для того чтобы убедится что эран живой. Сейчас это может в фоне падать. 

Вообще, мы не добавляем ignore правил, если ситуация по другому не решается (такую надо поискать, в нашем случае решается) то оставляем коммент почему игнорим

2023-07-03 16:01 UTC, Demezy commented on lib/auth_service/auth_service.dart
> +}
вероятно, нам нужен еще какой нибудь метод isAuthenticated() или типо того. Чтобы залогинившись отднажны _экран_ логина пропускался (а вдруг мы на него перейдем где нибудь). В случае мока норм, что токен нигде не лежит и мы при закрытии _приложения_ логинимся заново

2023-07-03 16:01 UTC, Demezy commented on lib/email_password_login/email_password_login.dart
> +      await Navigator.push<void>(
push = можем веруться на экран (например кнопкой назад)
go (вроде так) = просто переходем без возврата (не добавяем в стак)

сейчас мы можем вернуться на экран логина заново

2023-07-03 16:18 UTC, frog-da commented on lib/email_password_login/email_password_login.dart
> +      await Navigator.push<void>(
переделаю на go, спасибо за подсказку, но мы не можем сейчас вернуться на экран логина тк я делаю pop